name: Publish output

on:
  workflow_dispatch: {}
  schedule:
    - cron: '2 15 1 * *'

jobs:
  publish_output:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: main
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Setup git access
      run: |
        git config --global user.name 'Costas Basdekis'
        git config --global user.email 'costas@basdekis.io'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
    - name: Publish
      env:
        FACTORIO_MOD_API_SERVICE_TOKEN: ${{ secrets.FACTORIO_MOD_API_SERVICE_TOKEN }}
        FACTORIO_MOD_API_SERVICE_USERNAME: ${{ secrets.FACTORIO_MOD_API_SERVICE_USERNAME }}
      run: ./publish_output.sh
